// clippy returned error on autogenerated content
// error: all variants have the same prefix: `State`
//   --> limitador-server/src/envoy_rls/protobufs/././envoy.config.core.v3.rs:28:5
#![allow(clippy::all)]
mod envoy_types;
pub mod server;
