---
version: '3.8'
services:
  envoy:
    image: envoyproxy/envoy:v1.20-latest
    depends_on:
      - upstream
      - limitador
    command:
      - /usr/local/bin/envoy
      - --config-path
      - /etc/envoy.yaml
      - --log-level
      - info
      - --component-log-level
      - http:debug,router:debug
      - --service-cluster
      - proxy
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
  envoy2:
    image: envoyproxy/envoy:v1.20-latest
    depends_on:
      - upstream
      - limitador
    command:
      - /usr/local/bin/envoy
      - --config-path
      - /etc/envoy.yaml
      - --log-level
      - info
      - --component-log-level
      - http:debug,router:debug
      - --service-cluster
      - proxy
    expose:
      - "80"
      - "8001"
    ports:
      - "18100:80"
      - "18101:8001"
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
  envoy3:
    image: envoyproxy/envoy:v1.20-latest
    depends_on:
      - upstream
      - limitador
    command:
      - /usr/local/bin/envoy
      - --config-path
      - /etc/envoy.yaml
      - --log-level
      - info
      - --component-log-level
      - http:debug,router:debug
      - --service-cluster
      - proxy
    expose:
      - "80"
      - "8001"
    ports:
      - "18200:80"
      - "18201:8001"
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
  upstream:
    image: kennethreitz/httpbin
