---
version: '3.8'
services:
  limitador:
    image: ${LIMITADOR_IMAGE:-limitador-testing}
    depends_on:
      - envoy
      - redis
    command:
      - limitador-server
      - --rls-ip
      - 0.0.0.0
      - --rls-port
      - "8081"
      - --http-ip
      - 0.0.0.0
      - --http-port
      - "8080"
      - -vvv
      - --grpc-reflection-service
      - /opt/kuadrant/limits/limits.yaml
      - redis
      - redis://redis:6379
    expose:
      - "8080"
      - "8081"
    ports:
      - "18080:8080"
      - "18081:8081"
    volumes:
      - ./limits.yaml:/opt/kuadrant/limits/limits.yaml
  redis:
    image: redis:5
