---
name: Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # ratchet:actions/checkout@v6
      - uses: supercharge/redis-github-action@bc274cb7238cd63a45029db04ee48c07a72609fd # ratchet:supercharge/redis-github-action@1.8.1
        with:
          redis-version: 7
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # ratchet:actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # ratchet:Swatinem/rust-cache@v2
      - uses: abelfodil/protoc-action@b540a249a18feedb02bfbfa655afa15255cf3dc6 # ratchet:abelfodil/protoc-action@v1
        with:
          protoc-version: "3.19.4"
      - run: cargo bench
