---
name: Build Image

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  MAIN_BRANCH_NAME: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build/Push the Container Image
        uses: ./.github/actions/build-image
        with:
          platforms: linux/amd64,linux/arm64
