---
name: License Scan

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  dump-github:
    name: Dump Github context
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  fossa-scan:
    name: Find license compliance and security issues
    if: github.repository == 'Kuadrant/limitador'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fossas/fossa-action@v1.4.0
        name: License Scan
        with:
          api-key: ${{secrets.FOSSA_API_TOKEN}}
          branch: ${{ github.head_ref || github.ref_name }}
          project: git+github.com/Kuadrant/limitador
      - uses: fossas/fossa-action@v1.4.0
        name: License test for issues
        with:
          api-key: ${{secrets.FOSSA_API_TOKEN}}
          run-tests: true
          project: git+github.com/Kuadrant/limitador
